-- 0022: sampling.draws.seed_source — seed provenance on every draw
-- (hardening pass 2026-07-13, docs/reviews/2026-07-13-hardening-pass.md:
-- "Client-suppliable sampling draw seeds recorded without provenance").
--
-- A draw's seed may be supplied by the caller (reproducibility across
-- systems) or generated by Headway's CSPRNG. The draw row is the agency's
-- FEDERAL EVIDENCE that the selection was random (FTA NTD Sampling Manual
-- §63.03(b)(1)), and Headway can only vouch for the randomness of a seed it
-- generated itself — so the record must say which happened:
--
--   'generated' — Headway produced the seed (secrets.token_hex, a
--                 cryptographic randomness source) and recorded it.
--   'client'    — the caller supplied the seed; the selection is
--                 reproducible from the recorded seed, but its randomness
--                 rests on how the caller produced it. The API surfaces
--                 this distinction in the draw's method text.
--
-- NULLABLE, no default, no backfill: sampling.draws is structurally
-- append-only (migration 0020 trigger — UPDATE is rejected), and pre-0022
-- rows genuinely did not record which case occurred. A NULL here honestly
-- means "drawn before seed provenance was captured"; inventing a value for
-- history would be a provenance lie. The API writes seed_source on every
-- draw from this migration on.

ALTER TABLE sampling.draws
    ADD COLUMN seed_source TEXT
        CHECK (seed_source IN ('client', 'generated'));

COMMENT ON COLUMN sampling.draws.seed_source IS
    'Seed provenance: ''generated'' (Headway CSPRNG) or ''client'' '
    '(caller-supplied). NULL only on draws recorded before migration 0022 '
    '— append-only history, never backfilled.';
