"""The installation signing key and the canonical certification document
(handoff 0019, design point B).

WHAT IS SIGNED — the canonicalization, byte-precise
----------------------------------------------------
A certification signs a single JSON document. The signed bytes are produced
by exactly this recipe (``canonical_bytes``), and NOTHING else:

    json.dumps(document, sort_keys=True, separators=(",", ":"),
               ensure_ascii=True, allow_nan=False).encode("utf-8")

Properties that make it canonical (deterministic — the same document object
always yields the same bytes):

- **sort_keys=True** — object keys in lexicographic order at every level;
- **separators=(",", ":")** — no whitespace anywhere;
- **ensure_ascii=True** — every non-ASCII character escaped ``\\uXXXX``, so
  the byte encoding is ASCII-stable regardless of platform;
- **allow_nan=False** — NaN/Infinity refused (they are not JSON);
- every VALUE in the document is a JSON string, number (int only — no
  floats ever enter the document; figures travel as their exact NUMERIC
  strings), object, array, true/false/null. The builder in
  routers/certify.py uses strings for all figures and timestamps.

The stored ``canonical_document`` column (migration 0030) holds exactly
these bytes decoded as UTF-8 text; verification re-encodes the stored text
as UTF-8 and verifies the Ed25519 signature over those bytes — so ANY
mutation of the stored document (or signature) fails verification loudly.

THE KEY — installation-held, never in the database or repository
----------------------------------------------------------------
Ed25519 (RFC 8032) via the ``cryptography`` package (pyca — licensed
"Apache-2.0 OR BSD-3-Clause", ADR-0001 tier 2 permissive; recorded in
pyproject.toml and checked by scripts/license_gate.py). The private key is
a 32-byte seed, sourced at first use from (highest precedence first):

1. ``HEADWAY_SIGNING_KEY`` — 64 hex characters in the environment (the
   Docker Compose path: generated by the installer into
   deploy/compose/.env, like HEADWAY_SESSION_SECRET);
2. ``HEADWAY_SIGNING_KEY_FILE`` — a path holding those 64 hex characters.
   If the file does not exist, it is GENERATED at first use (os.urandom(32),
   written mode 0600) — the "generated at install/first-use" path for bare
   deployments.

If neither variable is set, signing REFUSES (SigningKeyUnavailable → the
certify endpoint returns a plain-language 503 and certifies NOTHING — a
certification is never silently recorded unsigned).

Key fingerprint: ``"ed25519:" + SHA-256 hex of the 32-byte raw public
key`` — stored with every signature so a record names WHICH installation
key signed it. Rotating the key changes the fingerprint; previously signed
certificates keep verifying only against the key that signed them, so the
verify endpoint reports an honest ``key_mismatch`` verdict for records
signed by a key this installation no longer holds (never a false
"tampered", never a false "verified").

HONEST SCOPE (stated on the certificate itself, design point B.8): an
installation-held key proves integrity (the record has not changed since
signing) and attribution within this system (this installation, this
signed-in certifying official). It is NOT PKI non-repudiation — the server
holds the key, not the certifier personally. Per-certifier keys (WebAuthn)
are the documented v1.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
from dataclasses import dataclass

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

ENV_KEY = "HEADWAY_SIGNING_KEY"
ENV_KEY_FILE = "HEADWAY_SIGNING_KEY_FILE"

ALGORITHM = "ed25519"

#: The seed is exactly 32 bytes = 64 hex characters (RFC 8032 Ed25519).
_SEED_HEX_LENGTH = 64


class SigningKeyUnavailable(RuntimeError):
    """No signing key is configured (or the configured one is malformed).

    Callers must fail the signing action loudly — a certification is never
    recorded unsigned because the key was missing.
    """


class SigningKeyMalformed(SigningKeyUnavailable):
    """A key source exists but does not hold 64 hex characters."""


def canonical_bytes(document: dict) -> bytes:
    """THE canonicalization (module docstring): deterministic JSON bytes.

    Refuses (TypeError/ValueError) anything json.dumps cannot serialize or
    a NaN/Infinity — a document that cannot canonicalize deterministically
    is never signed.
    """
    return json.dumps(
        document,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("utf-8")


def receipt_sha256(document: dict) -> str:
    """SHA-256 hex over the canonical bytes of one figure's receipt dict —
    the 'receipt hash' each certified figure carries inside the signed
    document (the recipe is canonical_bytes, so the hash is deterministic
    and independently recomputable from the served figure)."""
    return hashlib.sha256(canonical_bytes(document)).hexdigest()


def fingerprint_public_key(public_key: Ed25519PublicKey) -> str:
    """'ed25519:' + SHA-256 hex of the 32-byte raw public key."""
    from cryptography.hazmat.primitives.serialization import (
        Encoding,
        PublicFormat,
    )

    raw = public_key.public_bytes(Encoding.Raw, PublicFormat.Raw)
    return f"{ALGORITHM}:{hashlib.sha256(raw).hexdigest()}"


@dataclass(frozen=True)
class InstallationSigner:
    """The loaded installation key: sign, verify, and self-identify."""

    _private_key: Ed25519PrivateKey
    key_fingerprint: str

    def sign(self, document: dict) -> tuple[str, bytes]:
        """Sign a document dict.

        Returns ``(signature_base64, canonical_document_bytes)`` — the
        caller stores the canonical bytes (as UTF-8 text) and the base64
        signature together with ``key_fingerprint``.
        """
        payload = canonical_bytes(document)
        signature = self._private_key.sign(payload)
        return base64.b64encode(signature).decode("ascii"), payload

    def verify(self, canonical_document_text: str, signature_base64: str) -> bool:
        """True iff ``signature_base64`` is this key's valid Ed25519
        signature over the UTF-8 bytes of ``canonical_document_text``.
        Malformed base64 or a wrong signature returns False (the caller
        reports the loud plain-language verdict) — never raises for
        content reasons."""
        try:
            signature = base64.b64decode(
                signature_base64.encode("ascii"), validate=True
            )
        except Exception:
            return False
        try:
            self._private_key.public_key().verify(
                signature, canonical_document_text.encode("utf-8")
            )
        except InvalidSignature:
            return False
        return True


def _seed_from_hex(seed_hex: str, source: str) -> bytes:
    seed_hex = seed_hex.strip()
    if len(seed_hex) != _SEED_HEX_LENGTH:
        raise SigningKeyMalformed(
            f"The signing key in {source} must be exactly "
            f"{_SEED_HEX_LENGTH} hexadecimal characters (a 32-byte Ed25519 "
            f"seed, e.g. from `openssl rand -hex 32`); found "
            f"{len(seed_hex)} characters. The key itself is never logged."
        )
    try:
        return bytes.fromhex(seed_hex)
    except ValueError as exc:
        raise SigningKeyMalformed(
            f"The signing key in {source} is not valid hexadecimal. "
            f"Generate one with `openssl rand -hex 32`. The key itself is "
            f"never logged."
        ) from exc


def load_signer(environ=os.environ) -> InstallationSigner:
    """Load (or first-use-generate) the installation signing key.

    Precedence and generation rules per the module docstring. Raises
    SigningKeyUnavailable/SigningKeyMalformed — callers translate to a
    plain-language 503 and refuse the action.
    """
    seed_hex = environ.get(ENV_KEY, "").strip()
    if seed_hex:
        seed = _seed_from_hex(seed_hex, f"the {ENV_KEY} environment variable")
    else:
        key_file = environ.get(ENV_KEY_FILE, "").strip()
        if not key_file:
            raise SigningKeyUnavailable(
                f"No certification signing key is configured. Set {ENV_KEY} "
                f"(64 hex characters, e.g. `openssl rand -hex 32` — the "
                f"installer writes this into deploy/compose/.env) or "
                f"{ENV_KEY_FILE} (a secret-file path; generated on first "
                f"use if absent). The key lives ONLY in the environment or "
                f"secret file — never in the database or the repository."
            )
        if os.path.exists(key_file):
            with open(key_file, "r", encoding="ascii") as fh:
                seed = _seed_from_hex(fh.read(), f"the key file {key_file!r}")
        else:
            # First use on this installation: generate and persist, 0600.
            seed = os.urandom(32)
            fd = os.open(key_file, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            with os.fdopen(fd, "w", encoding="ascii") as fh:
                fh.write(seed.hex() + "\n")
    private_key = Ed25519PrivateKey.from_private_bytes(seed)
    return InstallationSigner(
        _private_key=private_key,
        key_fingerprint=fingerprint_public_key(private_key.public_key()),
    )


def get_signer(app) -> InstallationSigner:
    """The app-cached installation signer (loaded at first signing use —
    the 'first-use' half of install/first-use key generation). Tests inject
    ``app.state.signer`` directly or point the env vars at a temp file."""
    signer = getattr(app.state, "signer", None)
    if signer is None:
        signer = load_signer()
        app.state.signer = signer
    return signer
