-- =========================================================================
-- 01-create-view.sql — the Headway view: the view is the contract.
-- Generated by tools/view-ddl from adapters/tripspark/streets/mapping.v0.yaml
-- (adapter source label: tripspark_streets). Do not hand-edit the column list
-- or its order — Headway reads these exact 18 columns, in this
-- exact order, and refuses anything else (explicit columns only, never
-- the select-everything shorthand).
--
-- BEFORE RUNNING: replace every name that starts with FILL_IN_
-- with the real name from YOUR vendor database (your vendor's data
-- dictionary has them, or ask your Headway contact). The words after
-- "AS" must NOT be changed — they are the contract.
--
-- Dates and times: Headway refuses to guess date formats, so date/time
-- columns are converted to text HERE, in the view, in the exact format
-- the adapter declares. If any of your other columns is a decimal or
-- float, wrap it in CONVERT(varchar(32), ...) the same way — Headway
-- reports an error naming the column if a raw one slips through.
-- =========================================================================
USE [FILL_IN_YOUR_DATABASE_NAME];
GO

CREATE VIEW [dbo].[vw_headway_apc]
AS
SELECT
    src.[FILL_IN_VehicleLocationAPCKey] AS [VehicleLocationAPCKey],
    src.[FILL_IN_VehicleName] AS [VehicleName],
    src.[FILL_IN_TotalCount] AS [TotalCount],
    src.[FILL_IN_BoardCount] AS [BoardCount],
    src.[FILL_IN_AlightCount] AS [AlightCount],
    src.[FILL_IN_UnmodifiedAlightCount] AS [UnmodifiedAlightCount],
    src.[FILL_IN_APCSource] AS [APCSource],
    src.[FILL_IN_IsTripper] AS [IsTripper],
    src.[FILL_IN_IsDetour] AS [IsDetour],
    src.[FILL_IN_TripName] AS [TripName],
    src.[FILL_IN_RouteName] AS [RouteName],
    src.[FILL_IN_RouteShortName] AS [RouteShortName],
    src.[FILL_IN_PatternName] AS [PatternName],
    src.[FILL_IN_StopName] AS [StopName],
    src.[FILL_IN_StopCode] AS [StopCode],
    src.[FILL_IN_PatternPointRank] AS [PatternPointRank],
    src.[FILL_IN_DirectionKey] AS [DirectionKey],
    CONVERT(varchar(19), src.[FILL_IN_EventDateISO], 126) AS [EventDateISO]  -- date as text, exactly '%Y-%m-%dT%H:%M:%S'
FROM [FILL_IN_YourSchema].[FILL_IN_YourApcTable] AS src;
GO
