-- =========================================================================
-- 02-create-login-and-grant.sql — the read-only account Headway signs
-- in with. Generated by tools/view-ddl.
--
-- BEFORE RUNNING:
--   1. Replace FILL_IN_YOUR_DATABASE_NAME with your database's name
--      (the same one you used in 01-create-view.sql).
--   2. Replace PASTE_A_NEW_STRONG_PASSWORD_HERE with a NEW strong
--      password. Write it down somewhere safe — it goes into Headway's
--      configuration later, and it is never sent by email.
--
-- What this deliberately does NOT do: no table access, no write access,
-- no admin role. The headway_ro account can read the one Headway view and
-- nothing else — that is the whole point.
-- =========================================================================
USE [master];
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'headway_ro')
    CREATE LOGIN [headway_ro]
    WITH PASSWORD = N'PASTE_A_NEW_STRONG_PASSWORD_HERE',
         CHECK_POLICY = ON;
GO

USE [FILL_IN_YOUR_DATABASE_NAME];
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'headway_ro')
    CREATE USER [headway_ro] FOR LOGIN [headway_ro];
GO

GRANT SELECT ON [dbo].[vw_headway_apc] TO [headway_ro];
GO
