-- =========================================================================
-- 03-verify-view.sql — a read-only check that the view works.
-- Generated by tools/view-ddl. Safe to run any time; it changes nothing.
-- Every column is listed explicitly (never the select-everything
-- shorthand).
-- =========================================================================
USE [FILL_IN_YOUR_DATABASE_NAME];
GO

SELECT TOP (5)
    [VehicleLocationAPCKey],
    [VehicleName],
    [TotalCount],
    [BoardCount],
    [AlightCount],
    [UnmodifiedAlightCount],
    [APCSource],
    [IsTripper],
    [IsDetour],
    [TripName],
    [RouteName],
    [RouteShortName],
    [PatternName],
    [StopName],
    [StopCode],
    [PatternPointRank],
    [DirectionKey],
    [EventDateISO]
FROM [dbo].[vw_headway_apc]
ORDER BY [VehicleLocationAPCKey] DESC;
GO

SELECT COUNT_BIG(*) AS total_rows_in_view
FROM [dbo].[vw_headway_apc];
GO
